project:
  type: website
  output-dir: docs
  
website: 
  title: "today"
  navbar:
    left: 
      -  href: index.qmd
         text: Home
      -  book_info.qmd
      
      

format:
  html:
    theme: cosmo
    css: styles.css